# config.yaml

data:
  train_lr: tiles/lr/train/**/*.npy
  train_hr: tiles/hr/train/**/*.npy
  val_lr:   tiles/lr/val/**/*.npy
  val_hr:   tiles/hr/val/**/*.npy
  test_lr:  tiles/lr/test/**/*.npy
  test_hr:  tiles/hr/test/**/*.npy
  norm: oe                  

vae:
  z_ch: 64                  
  base_ch: 64               
  epochs: 100
  batch_size: 2
  lr: 0.0002                 
  save_dir: ./runs/sr_vae

srvae:
  scale: 1

loss:
  rec_w: 0.50
  ssim_w: 0.25
  grad_w: 0.25
  beta_start: 0.0
  beta_end: 0.000001
  kl_warmup_epochs: 60